# ========
# VALIDATE
# ========

name: Validate

# Activation Events
# =================

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"
  workflow_dispatch:

# Jobs
# ====

jobs:
  # Build
  # -----

  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
          npm run build

  # Dist
  # ----

  check-dist: # Check whether the checked-in dist actually matches what we expect it to be
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: npm run dev

      # If dist/index.js was different than expected, push changes
      - name: check for changes
        id: git-diff
        if: ${{ github.ref == 'main' }}
        run: |
          if git diff --exit-code; then
            echo "::set-output name=changes_exist::false"
          else
            echo "::set-output name=changes_exist::true"
          fi
      - name: push
        if: ${{ steps.git-diff.outputs.changes_exist == 'true' }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Build 📦'
          git push

  # Test
  # ====

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          url: https://github.com/Shresht7/web-screenshot-action
